imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
        uglifycss:
            bin: %kernel.root_dir%/../node_modules/uglifycss/uglifycss

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

hearsay_require_js:
    require_js_src:  /bundles/maxplayerfrontend/vendor/requirejs/require.js
    initialize_template: HearsayRequireJSBundle::initialize.html.twig
    base_url:  /bundles/maxplayerfrontend/js/modules
    base_dir: %kernel.root_dir%/../src/Maxplayer/FrontendBundle/Resources/public/js/modules # Required
    paths:
        jquery:
            location: /bundles/maxplayerfrontend/vendor/jquery/dist/jquery.min
            external: true
        underscore:
            location: /bundles/maxplayerfrontend/vendor/underscore/underscore-min
            external: true
        backbone:
            location: /bundles/maxplayerfrontend/vendor/backbone/backbone-min
            external: true
        soundmanager:
            location: /bundles/maxplayerfrontend/vendor/SoundManager2/script/soundmanager2-jsmin
            external: true
        bootstrap:
            location: /bundles/maxplayerfrontend/vendor/bootstrap/dist/js/bootstrap.min
            external: true
        spotify:
            location: /bundles/maxplayerfrontend/vendor/spotify-web-api-js/src/spotify-web-api
            external: true
        text:
            location: /bundles/maxplayerfrontend/vendor/text/text
            external: true
        template:
            location: /bundles/maxplayerfrontend/js/templates
            external: true
    shim:
        bootstrap:
            deps: [jquery]
        backbone:
            deps: ['underscore', 'jquery']
    optimizer:
        path: %kernel.root_dir%/../node_modules/requirejs/bin/r.js
        hide_unoptimized_assets: false
        options:
            removeCombined: true
            name: main
            optimize: uglify2
            uglify2:
                output:
                    beautify: false
                compress:
                    sequences: true
                    global_defs:
                        DEBUG: false
                warnings: true
                mangle: false

glifery_vk_oauth_token:
    app_key: 4617137
    app_secret: wjv0oh8UWSJVHpbSSqLG
    app_scope:
        - friends
        - photos
        - audio
        - video
        - docs
        - status
        - email
        - notifications
        - stats
        - offline
    token_table: oauth_token