maxplayer_frontend:
    resource: "@MaxplayerFrontendBundle/Resources/config/routing.yml"
    prefix:   /

maxplayer_rest:
    resource: "@MaxplayerRestBundle/Resources/config/routing.yml"
    prefix:   /rest

maxplayer_vk_request:
    resource: "@MaxplayerVkRequestBundle/Resources/config/routing.yml"
    prefix:   /

maxplayer_vk_api:
    resource: "@MaxplayerVkApiBundle/Resources/config/routing.yml"
    prefix:   /vk

maxplayer_test:
    resource: "@MaxplayerTestBundle/Resources/config/routing.yml"
    prefix:   /

