glifery_vk_oauth_token:
    resource: "@GliferyVkOAuthTokenBundle/Resources/config/routing.yml"
    prefix:   /tools/vk_oauth

maxplayer_frontend:
    resource: "@MaxplayerFrontendBundle/Resources/config/routing.yml"
    prefix:   /

maxplayer_rest:
    resource: "@MaxplayerRestBundle/Resources/config/routing.yml"
    prefix:   /rest

maxplayer_vk_request:
    resource: "@MaxplayerVkRequestBundle/Resources/config/routing.yml"
    prefix:   /

maxplayer_test:
    resource: "@MaxplayerTestBundle/Resources/config/routing.yml"
    prefix:   /

