services:
    maxplayer_vk_request.vk_gate:
        class: Maxplayer\VkRequestBundle\Service\VkGate
        arguments: [@maxplayer_vk_api.vk_transport, @maxplayer_vk_request.transform_manager]
    maxplayer_vk_request.transform_manager:
        class: Maxplayer\VkRequestBundle\Service\TransformManager
        calls:
            - [ registerTransformer, [audio.search, Maxplayer\VkRequestBundle\Transformer\AudioTransformer]]
    maxplayer_vk_request.vk_repository:
        class: Maxplayer\VkRequestBundle\Service\VkRepository
        arguments: [@maxplayer_vk_request.vk_gate]