maxplayer_test_vk_auth:
    path:     /test/vk/auth
    defaults: { _controller: MaxplayerTestBundle:Vk:auth }
maxplayer_test_vk_request:
    path:     /test/vk/request
    defaults: { _controller: MaxplayerTestBundle:Vk:request }
maxplayer_test_rest_track:
    path:     /test/rest/track
    defaults: { _controller: MaxplayerTestBundle:Rest:track }
maxplayer_test_frontend_assets:
    path:     /test/frontend/assets
    defaults: { _controller: MaxplayerTestBundle:Frontend:index }