maxplayer_test_homepage:
    path:     /hello/{name}
    defaults: { _controller: MaxplayerTestBundle:Default:index }
maxplayer_test_vk_auth:
    path:     /test/vk/auth
    defaults: { _controller: MaxplayerTestBundle:Vk:auth }
maxplayer_test_vk_sound:
    path:     /test/vk/sound
    defaults: { _controller: MaxplayerTestBundle:Vk:sound }